### ISSUE TITLE
Enhance recovery script execution

### ISSUE THREAD

**Issue by miyconst** [Starcounter/cbwatchdog#1]
- It should wait till the recovery script finishes execution.
- It should be possible to configure whether to start script headless or not.

**Comment by ubbeK** [comment]
> It should be possible to configure whether to start script headless or not.

Has been implemented: set `"noConsoleForRecoveryScript": "true",` in config.json file to activating it.

> It should wait till the recovery script finishes execution.

This doesn't make sense when there is a `"recoveryPauseInterval"` attribute to set in the config.json file. Why would we wait infinitely (untill process is done) + `recoveryPauseInterval` milliseconds when running the `recoveryBatch` file. There is a [commit in branch issue1](https://github.com/Starcounter/cbwatchdog/commit/a7f5abfd4383adb775f16ceb44787e448191b5b9) that does this.
Isn't it better to run  `staradmin --database=<DatabaseName> stop host` in the `recoveryBatch` file in order to get a known `recoveryPauseInterval`?

**Comment by miyconst** [comment]
>Isn't it better to run  `staradmin --database=<DatabaseName> stop host` in the `recoveryBatch` file in order to get a known `recoveryPauseInterval`?

Well, the thing is that when there are background threads with active TCP connections running, it takes a while to kill those and stop database. The time spent for stopping a database is not predictable.

That is why I want to wait for the script to finish execution, and only then check for the recovery state. Otherwise it may end up in an infinite loop, when the old script is still executing, but the Watchdog has started another one, and then another one.

There could be another settings for how long it's allowed to wait for the recovery script to finish.

**Comment by miyconst** [comment]
>Has been implemented: set `"noConsoleForRecoveryScript": "true"`, in `config.json` file to activating it.

So, by default the recovery scripts will be executed with visible console window, right?

**Comment by ubbeK** [comment]
> So, by default the recovery scripts will be executed with visible console window, right?

Yes, it will show by default. Set `"noConsoleForRecoveryScript": "true"` in order to hide it.

**Comment by ubbeK** [comment]
> The time spent for stopping a database is not predictable.

OK

> There could be another settings for how long it's allowed to wait for the recovery script to finish.

That is what I would like to do here (change INFINITE to some recoveryExecutionTimeout): 
```c#
PrintInfo("CreateProcessAsUser has been executed");
if (WaitForSingleObject(procInfo.hProcess, INFINITE) == WAIT_OBJECT_0)
{
    PrintInfo("CreateProcessAsUser PASSED");
}
else
{
    PrintInfo("CreateProcessAsUser FAILED");
    // TODO: Kill the process.
}
```

and then remove the hole idea of `recoveryPauseInterval`.

**Comment by miyconst** [comment]
That sounds as a good solution for me. Please implement.

**Comment by ubbeK** [comment]
This issue has been implemented,

new configuration json-file structure:
```json
{
  "healthCheckInterval": "10000",
  "recoveryExecutionTimeout": "300000",
  "noConsoleForRecoveryScript": "false",
  "criticalCounts": "10",
  "recoveryItems": [
    {
      "recoveryBatch": "cbwatchdog.bat",
      "scDatabase": "default",
      "processes": ["ProcessName"],
      "scAppNames": ["ApplicationName"]
    }
  ]
}
```

with default values:

```csharp
int healthCheckInterval = 10000; // number of milliseconds waiting between each check
int recoveryExecutionTimeout = 300000; // number of milliseconds before recoveryBatch is timeed out
int criticalCounts = 10; // number of times recoveryBatch may be executed in a row
bool noConsoleForRecoveryScript = false; // true: Show console for recoveryBatch, false: Do not show console for recoveryBatch
```
