### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/cbwatchdog#10]
* Make the part of how to start the service with arguments stand out more.
```
net start CustomBatchWatchdog /"C:\Watchdog\cbwatchdog.json" /CBWatchDog
```

As I understand, current default location of json-configuration file is where the `cbwatchdog` executable is located. Please confirm that and update the documentation

**Comment by ubbeK** [comment]
README.md needs to be restructured. It has a lot of unnecessary information and is hard to grasp. One should be able to go through step by step and get it working.

The first part should describe how to use this to restart `notepad`, kind of like it is today. But this means that the `cbwatchdog.bat` and `cbwatchdog.json` needs to be updated to not have any Starcounter specific functionality at all. Include how to diagnos the systemlog here and how to uninstall the service as well.

The second part should describe all fields in `cbwatchdog.json` and give a proper example on how to configurate it with the Starcounter server. This part should also include any possible arguments to the service itself and describe that fullpaths may used inside the json file. 

cc @iqbalskd

**Comment by iqbalskd** [comment]
Updated the readme.md file

**Comment by ubbeK** [comment]
It looks good as a whole but some minor changes are still needed.

* `recoveryBatch` explain that fullpath may be used here [somewhere](https://github.com/Starcounter/cbwatchdog/blob/master/README.md#defaults-and-obligatory-options)
* `Service is configured via cbwatchdog.json which must be put into %windir%/System32 (which usually is C:/windows/system32).` This is not true due to `net start CustomBatchWatchdog /"C:\Watchdog\cbwatchdog.json"`
* `recoveryPauseInterval ` is mentioned in the first paragraph, it doesn't exist anymore, Update this part.
* Add another paragraph with its own header below [Defaults and obligatory options](https://github.com/Starcounter/cbwatchdog/blob/master/README.md#defaults-and-obligatory-options) which describes briefly how and why it can be used with Starcounter. Simply whats its intentions are.

**Comment by iqbalskd** [comment]
Made the suggested changes.
