### ISSUE TITLE
Test and release

### ISSUE THREAD

**Issue by ubbeK** [Starcounter/cbwatchdog#11]
After https://github.com/Starcounter/cbwatchdog/issues/10 is done, please 
* review branch https://github.com/Starcounter/cbwatchdog/tree/careri and merge to master
* make some testing of the `cbwatchdog` as a whole
* bump the version
* release (don't forget to attach binaries as last time and to push a tag).

**Comment by iqbalskd** [comment]
Hi @ubbeK 
I have merged the careri branch into master, but the .Net framework runtime throws an error on starting the service. Even the previous release throwing the same error. So I am stuck here.

**Comment by ubbeK** [comment]
What error do you get?

**Comment by iqbalskd** [comment]
Tested the application, changed the `cbwatchdog.bat` to run the `notepad` and released a new version
